// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestBase struct {
	Msgid                string   `protobuf:"bytes,1,opt,name=msgid,proto3" json:"msgid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestBase) Reset()         { *m = RequestBase{} }
func (m *RequestBase) String() string { return proto.CompactTextString(m) }
func (*RequestBase) ProtoMessage()    {}
func (*RequestBase) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *RequestBase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestBase.Unmarshal(m, b)
}
func (m *RequestBase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestBase.Marshal(b, m, deterministic)
}
func (m *RequestBase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestBase.Merge(m, src)
}
func (m *RequestBase) XXX_Size() int {
	return xxx_messageInfo_RequestBase.Size(m)
}
func (m *RequestBase) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestBase.DiscardUnknown(m)
}

var xxx_messageInfo_RequestBase proto.InternalMessageInfo

func (m *RequestBase) GetMsgid() string {
	if m != nil {
		return m.Msgid
	}
	return ""
}

type Response struct {
	Msgid                string   `protobuf:"bytes,1,opt,name=msgid,proto3" json:"msgid,omitempty"`
	ErrorCode            int64    `protobuf:"varint,3,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Error                string   `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsgid() string {
	if m != nil {
		return m.Msgid
	}
	return ""
}

func (m *Response) GetErrorCode() int64 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type KeyValue struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyValue) Reset()         { *m = KeyValue{} }
func (m *KeyValue) String() string { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()    {}
func (*KeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *KeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValue.Unmarshal(m, b)
}
func (m *KeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValue.Marshal(b, m, deterministic)
}
func (m *KeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValue.Merge(m, src)
}
func (m *KeyValue) XXX_Size() int {
	return xxx_messageInfo_KeyValue.Size(m)
}
func (m *KeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValue proto.InternalMessageInfo

func (m *KeyValue) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *KeyValue) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type RequestKVSGetList struct {
	Req                  *RequestBase `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	Keys                 [][]byte     `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RequestKVSGetList) Reset()         { *m = RequestKVSGetList{} }
func (m *RequestKVSGetList) String() string { return proto.CompactTextString(m) }
func (*RequestKVSGetList) ProtoMessage()    {}
func (*RequestKVSGetList) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *RequestKVSGetList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestKVSGetList.Unmarshal(m, b)
}
func (m *RequestKVSGetList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestKVSGetList.Marshal(b, m, deterministic)
}
func (m *RequestKVSGetList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestKVSGetList.Merge(m, src)
}
func (m *RequestKVSGetList) XXX_Size() int {
	return xxx_messageInfo_RequestKVSGetList.Size(m)
}
func (m *RequestKVSGetList) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestKVSGetList.DiscardUnknown(m)
}

var xxx_messageInfo_RequestKVSGetList proto.InternalMessageInfo

func (m *RequestKVSGetList) GetReq() *RequestBase {
	if m != nil {
		return m.Req
	}
	return nil
}

func (m *RequestKVSGetList) GetKeys() [][]byte {
	if m != nil {
		return m.Keys
	}
	return nil
}

type ResponseKVSGetList struct {
	Resp                 *Response   `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	Kvs                  []*KeyValue `protobuf:"bytes,2,rep,name=kvs,proto3" json:"kvs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ResponseKVSGetList) Reset()         { *m = ResponseKVSGetList{} }
func (m *ResponseKVSGetList) String() string { return proto.CompactTextString(m) }
func (*ResponseKVSGetList) ProtoMessage()    {}
func (*ResponseKVSGetList) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *ResponseKVSGetList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseKVSGetList.Unmarshal(m, b)
}
func (m *ResponseKVSGetList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseKVSGetList.Marshal(b, m, deterministic)
}
func (m *ResponseKVSGetList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseKVSGetList.Merge(m, src)
}
func (m *ResponseKVSGetList) XXX_Size() int {
	return xxx_messageInfo_ResponseKVSGetList.Size(m)
}
func (m *ResponseKVSGetList) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseKVSGetList.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseKVSGetList proto.InternalMessageInfo

func (m *ResponseKVSGetList) GetResp() *Response {
	if m != nil {
		return m.Resp
	}
	return nil
}

func (m *ResponseKVSGetList) GetKvs() []*KeyValue {
	if m != nil {
		return m.Kvs
	}
	return nil
}

type RequestKVSSetList struct {
	Req                  *RequestBase `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	Kvs                  []*KeyValue  `protobuf:"bytes,2,rep,name=kvs,proto3" json:"kvs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RequestKVSSetList) Reset()         { *m = RequestKVSSetList{} }
func (m *RequestKVSSetList) String() string { return proto.CompactTextString(m) }
func (*RequestKVSSetList) ProtoMessage()    {}
func (*RequestKVSSetList) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *RequestKVSSetList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestKVSSetList.Unmarshal(m, b)
}
func (m *RequestKVSSetList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestKVSSetList.Marshal(b, m, deterministic)
}
func (m *RequestKVSSetList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestKVSSetList.Merge(m, src)
}
func (m *RequestKVSSetList) XXX_Size() int {
	return xxx_messageInfo_RequestKVSSetList.Size(m)
}
func (m *RequestKVSSetList) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestKVSSetList.DiscardUnknown(m)
}

var xxx_messageInfo_RequestKVSSetList proto.InternalMessageInfo

func (m *RequestKVSSetList) GetReq() *RequestBase {
	if m != nil {
		return m.Req
	}
	return nil
}

func (m *RequestKVSSetList) GetKvs() []*KeyValue {
	if m != nil {
		return m.Kvs
	}
	return nil
}

type ResponseKVSSetList struct {
	Resp                 *Response `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ResponseKVSSetList) Reset()         { *m = ResponseKVSSetList{} }
func (m *ResponseKVSSetList) String() string { return proto.CompactTextString(m) }
func (*ResponseKVSSetList) ProtoMessage()    {}
func (*ResponseKVSSetList) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *ResponseKVSSetList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseKVSSetList.Unmarshal(m, b)
}
func (m *ResponseKVSSetList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseKVSSetList.Marshal(b, m, deterministic)
}
func (m *ResponseKVSSetList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseKVSSetList.Merge(m, src)
}
func (m *ResponseKVSSetList) XXX_Size() int {
	return xxx_messageInfo_ResponseKVSSetList.Size(m)
}
func (m *ResponseKVSSetList) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseKVSSetList.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseKVSSetList proto.InternalMessageInfo

func (m *ResponseKVSSetList) GetResp() *Response {
	if m != nil {
		return m.Resp
	}
	return nil
}

type RequestKVSDeleteList struct {
	Req                  *RequestBase `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	Keys                 [][]byte     `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RequestKVSDeleteList) Reset()         { *m = RequestKVSDeleteList{} }
func (m *RequestKVSDeleteList) String() string { return proto.CompactTextString(m) }
func (*RequestKVSDeleteList) ProtoMessage()    {}
func (*RequestKVSDeleteList) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7}
}

func (m *RequestKVSDeleteList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestKVSDeleteList.Unmarshal(m, b)
}
func (m *RequestKVSDeleteList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestKVSDeleteList.Marshal(b, m, deterministic)
}
func (m *RequestKVSDeleteList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestKVSDeleteList.Merge(m, src)
}
func (m *RequestKVSDeleteList) XXX_Size() int {
	return xxx_messageInfo_RequestKVSDeleteList.Size(m)
}
func (m *RequestKVSDeleteList) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestKVSDeleteList.DiscardUnknown(m)
}

var xxx_messageInfo_RequestKVSDeleteList proto.InternalMessageInfo

func (m *RequestKVSDeleteList) GetReq() *RequestBase {
	if m != nil {
		return m.Req
	}
	return nil
}

func (m *RequestKVSDeleteList) GetKeys() [][]byte {
	if m != nil {
		return m.Keys
	}
	return nil
}

type ResponseKVSDeleteList struct {
	Resp                 *Response `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ResponseKVSDeleteList) Reset()         { *m = ResponseKVSDeleteList{} }
func (m *ResponseKVSDeleteList) String() string { return proto.CompactTextString(m) }
func (*ResponseKVSDeleteList) ProtoMessage()    {}
func (*ResponseKVSDeleteList) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{8}
}

func (m *ResponseKVSDeleteList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseKVSDeleteList.Unmarshal(m, b)
}
func (m *ResponseKVSDeleteList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseKVSDeleteList.Marshal(b, m, deterministic)
}
func (m *ResponseKVSDeleteList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseKVSDeleteList.Merge(m, src)
}
func (m *ResponseKVSDeleteList) XXX_Size() int {
	return xxx_messageInfo_ResponseKVSDeleteList.Size(m)
}
func (m *ResponseKVSDeleteList) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseKVSDeleteList.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseKVSDeleteList proto.InternalMessageInfo

func (m *ResponseKVSDeleteList) GetResp() *Response {
	if m != nil {
		return m.Resp
	}
	return nil
}

func init() {
	proto.RegisterType((*RequestBase)(nil), "proto.RequestBase")
	proto.RegisterType((*Response)(nil), "proto.Response")
	proto.RegisterType((*KeyValue)(nil), "proto.KeyValue")
	proto.RegisterType((*RequestKVSGetList)(nil), "proto.RequestKVSGetList")
	proto.RegisterType((*ResponseKVSGetList)(nil), "proto.ResponseKVSGetList")
	proto.RegisterType((*RequestKVSSetList)(nil), "proto.RequestKVSSetList")
	proto.RegisterType((*ResponseKVSSetList)(nil), "proto.ResponseKVSSetList")
	proto.RegisterType((*RequestKVSDeleteList)(nil), "proto.RequestKVSDeleteList")
	proto.RegisterType((*ResponseKVSDeleteList)(nil), "proto.ResponseKVSDeleteList")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x90, 0xc1, 0x4f, 0xf2, 0x40,
	0x10, 0xc5, 0x53, 0xb6, 0x7c, 0x81, 0x81, 0x2f, 0xea, 0x04, 0x93, 0x1e, 0x3c, 0xd4, 0xc5, 0x43,
	0x4f, 0x1c, 0xf0, 0x64, 0xe2, 0x49, 0x4d, 0x3c, 0xa0, 0x89, 0xd9, 0x1a, 0x4e, 0x5c, 0x6a, 0x98,
	0x10, 0x52, 0x70, 0xcb, 0xee, 0x42, 0xd2, 0xff, 0xde, 0xec, 0x2e, 0xd8, 0xf5, 0x60, 0x02, 0xf1,
	0xd4, 0x9d, 0x79, 0xf3, 0x5e, 0x7e, 0xaf, 0xf0, 0x7f, 0x4d, 0x5a, 0x17, 0x0b, 0x1a, 0x55, 0x4a,
	0x1a, 0x89, 0x6d, 0xf7, 0xe1, 0x43, 0xe8, 0x09, 0xda, 0x6c, 0x49, 0x9b, 0x87, 0x42, 0x13, 0x0e,
	0xa0, 0xbd, 0xd6, 0x8b, 0xe5, 0x3c, 0x89, 0xd2, 0x28, 0xeb, 0x0a, 0x3f, 0xf0, 0x77, 0xe8, 0x08,
	0xd2, 0x95, 0xfc, 0xfc, 0xed, 0x02, 0xaf, 0xa0, 0x4b, 0x4a, 0x49, 0xf5, 0x28, 0xe7, 0x94, 0xb0,
	0x34, 0xca, 0x98, 0x68, 0x16, 0xd6, 0xe3, 0x86, 0x24, 0xf6, 0x1e, 0x37, 0xf0, 0x31, 0x74, 0x26,
	0x54, 0x4f, 0x8b, 0xd5, 0x96, 0xf0, 0x1c, 0x58, 0x49, 0xb5, 0xcb, 0xec, 0x0b, 0xfb, 0xb4, 0x9e,
	0x9d, 0x95, 0x92, 0x96, 0xdb, 0xf9, 0x81, 0xbf, 0xc2, 0xc5, 0x1e, 0x77, 0x32, 0xcd, 0x9f, 0xc9,
	0xbc, 0x2c, 0xb5, 0xc1, 0x1b, 0x60, 0x8a, 0x36, 0xce, 0xdc, 0x1b, 0xa3, 0xef, 0x37, 0x0a, 0x5a,
	0x09, 0x2b, 0x23, 0x42, 0x5c, 0x52, 0xad, 0x93, 0x56, 0xca, 0xb2, 0xbe, 0x70, 0x6f, 0x3e, 0x03,
	0x3c, 0x14, 0x0b, 0xf2, 0x86, 0x10, 0x2b, 0xd2, 0xd5, 0x3e, 0xf0, 0xec, 0x3b, 0xd0, 0x1f, 0x0a,
	0x27, 0xe2, 0x35, 0xb0, 0x72, 0xe7, 0xd3, 0x9a, 0x9b, 0x43, 0x1f, 0x61, 0x35, 0x3e, 0x0b, 0x61,
	0xf3, 0x93, 0x60, 0x8f, 0x48, 0xbf, 0xfb, 0xc1, 0x9e, 0x9f, 0xc0, 0xce, 0xdf, 0x60, 0xd0, 0x80,
	0x3d, 0xd1, 0x8a, 0x0c, 0xfd, 0xf1, 0x47, 0xde, 0xc3, 0x65, 0x00, 0x13, 0x44, 0x1e, 0xc3, 0xf3,
	0xf1, 0xcf, 0x6d, 0x6f, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x74, 0x6e, 0xf7, 0xef, 0xa3, 0x02,
	0x00, 0x00,
}
