// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PropertyType int32

const (
	PropertyType_stats      PropertyType = 0
	PropertyType_writedelay PropertyType = 1
	PropertyType_iostats    PropertyType = 2
)

var PropertyType_name = map[int32]string{
	0: "stats",
	1: "writedelay",
	2: "iostats",
}

var PropertyType_value = map[string]int32{
	"stats":      0,
	"writedelay": 1,
	"iostats":    2,
}

func (x PropertyType) String() string {
	return proto.EnumName(PropertyType_name, int32(x))
}

func (PropertyType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

type ReqBase struct {
	Msgid                string   `protobuf:"bytes,1,opt,name=msgid,proto3" json:"msgid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqBase) Reset()         { *m = ReqBase{} }
func (m *ReqBase) String() string { return proto.CompactTextString(m) }
func (*ReqBase) ProtoMessage()    {}
func (*ReqBase) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *ReqBase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqBase.Unmarshal(m, b)
}
func (m *ReqBase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqBase.Marshal(b, m, deterministic)
}
func (m *ReqBase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqBase.Merge(m, src)
}
func (m *ReqBase) XXX_Size() int {
	return xxx_messageInfo_ReqBase.Size(m)
}
func (m *ReqBase) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqBase.DiscardUnknown(m)
}

var xxx_messageInfo_ReqBase proto.InternalMessageInfo

func (m *ReqBase) GetMsgid() string {
	if m != nil {
		return m.Msgid
	}
	return ""
}

type RespBase struct {
	Msgid                string   `protobuf:"bytes,1,opt,name=msgid,proto3" json:"msgid,omitempty"`
	ErrorCode            int64    `protobuf:"varint,3,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Error                string   `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespBase) Reset()         { *m = RespBase{} }
func (m *RespBase) String() string { return proto.CompactTextString(m) }
func (*RespBase) ProtoMessage()    {}
func (*RespBase) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *RespBase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespBase.Unmarshal(m, b)
}
func (m *RespBase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespBase.Marshal(b, m, deterministic)
}
func (m *RespBase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespBase.Merge(m, src)
}
func (m *RespBase) XXX_Size() int {
	return xxx_messageInfo_RespBase.Size(m)
}
func (m *RespBase) XXX_DiscardUnknown() {
	xxx_messageInfo_RespBase.DiscardUnknown(m)
}

var xxx_messageInfo_RespBase proto.InternalMessageInfo

func (m *RespBase) GetMsgid() string {
	if m != nil {
		return m.Msgid
	}
	return ""
}

func (m *RespBase) GetErrorCode() int64 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *RespBase) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type KeyValue struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyValue) Reset()         { *m = KeyValue{} }
func (m *KeyValue) String() string { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()    {}
func (*KeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *KeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValue.Unmarshal(m, b)
}
func (m *KeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValue.Marshal(b, m, deterministic)
}
func (m *KeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValue.Merge(m, src)
}
func (m *KeyValue) XXX_Size() int {
	return xxx_messageInfo_KeyValue.Size(m)
}
func (m *KeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValue proto.InternalMessageInfo

func (m *KeyValue) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *KeyValue) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type ReqSet struct {
	Base                 *ReqBase  `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	DbName               string    `protobuf:"bytes,2,opt,name=dbName,proto3" json:"dbName,omitempty"`
	Kv                   *KeyValue `protobuf:"bytes,3,opt,name=kv,proto3" json:"kv,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ReqSet) Reset()         { *m = ReqSet{} }
func (m *ReqSet) String() string { return proto.CompactTextString(m) }
func (*ReqSet) ProtoMessage()    {}
func (*ReqSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *ReqSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSet.Unmarshal(m, b)
}
func (m *ReqSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSet.Marshal(b, m, deterministic)
}
func (m *ReqSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSet.Merge(m, src)
}
func (m *ReqSet) XXX_Size() int {
	return xxx_messageInfo_ReqSet.Size(m)
}
func (m *ReqSet) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSet.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSet proto.InternalMessageInfo

func (m *ReqSet) GetBase() *ReqBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *ReqSet) GetDbName() string {
	if m != nil {
		return m.DbName
	}
	return ""
}

func (m *ReqSet) GetKv() *KeyValue {
	if m != nil {
		return m.Kv
	}
	return nil
}

type ReqGet struct {
	Base                 *ReqBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	DbName               string   `protobuf:"bytes,2,opt,name=dbName,proto3" json:"dbName,omitempty"`
	Key                  []byte   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqGet) Reset()         { *m = ReqGet{} }
func (m *ReqGet) String() string { return proto.CompactTextString(m) }
func (*ReqGet) ProtoMessage()    {}
func (*ReqGet) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *ReqGet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqGet.Unmarshal(m, b)
}
func (m *ReqGet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqGet.Marshal(b, m, deterministic)
}
func (m *ReqGet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqGet.Merge(m, src)
}
func (m *ReqGet) XXX_Size() int {
	return xxx_messageInfo_ReqGet.Size(m)
}
func (m *ReqGet) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqGet.DiscardUnknown(m)
}

var xxx_messageInfo_ReqGet proto.InternalMessageInfo

func (m *ReqGet) GetBase() *ReqBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *ReqGet) GetDbName() string {
	if m != nil {
		return m.DbName
	}
	return ""
}

func (m *ReqGet) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type RespGet struct {
	Base                 *RespBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Kv                   *KeyValue `protobuf:"bytes,2,opt,name=kv,proto3" json:"kv,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RespGet) Reset()         { *m = RespGet{} }
func (m *RespGet) String() string { return proto.CompactTextString(m) }
func (*RespGet) ProtoMessage()    {}
func (*RespGet) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *RespGet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespGet.Unmarshal(m, b)
}
func (m *RespGet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespGet.Marshal(b, m, deterministic)
}
func (m *RespGet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespGet.Merge(m, src)
}
func (m *RespGet) XXX_Size() int {
	return xxx_messageInfo_RespGet.Size(m)
}
func (m *RespGet) XXX_DiscardUnknown() {
	xxx_messageInfo_RespGet.DiscardUnknown(m)
}

var xxx_messageInfo_RespGet proto.InternalMessageInfo

func (m *RespGet) GetBase() *RespBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *RespGet) GetKv() *KeyValue {
	if m != nil {
		return m.Kv
	}
	return nil
}

type ReqDelete struct {
	Base                 *ReqBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	DbName               string   `protobuf:"bytes,2,opt,name=dbName,proto3" json:"dbName,omitempty"`
	Key                  []byte   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqDelete) Reset()         { *m = ReqDelete{} }
func (m *ReqDelete) String() string { return proto.CompactTextString(m) }
func (*ReqDelete) ProtoMessage()    {}
func (*ReqDelete) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *ReqDelete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqDelete.Unmarshal(m, b)
}
func (m *ReqDelete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqDelete.Marshal(b, m, deterministic)
}
func (m *ReqDelete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqDelete.Merge(m, src)
}
func (m *ReqDelete) XXX_Size() int {
	return xxx_messageInfo_ReqDelete.Size(m)
}
func (m *ReqDelete) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqDelete.DiscardUnknown(m)
}

var xxx_messageInfo_ReqDelete proto.InternalMessageInfo

func (m *ReqDelete) GetBase() *ReqBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *ReqDelete) GetDbName() string {
	if m != nil {
		return m.DbName
	}
	return ""
}

func (m *ReqDelete) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type ReqGetByPrefix struct {
	Base                 *ReqBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	DbName               string   `protobuf:"bytes,2,opt,name=dbName,proto3" json:"dbName,omitempty"`
	Prefix               []byte   `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	LastKey              []byte   `protobuf:"bytes,4,opt,name=lastKey,proto3" json:"lastKey,omitempty"`
	Limit                int64    `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqGetByPrefix) Reset()         { *m = ReqGetByPrefix{} }
func (m *ReqGetByPrefix) String() string { return proto.CompactTextString(m) }
func (*ReqGetByPrefix) ProtoMessage()    {}
func (*ReqGetByPrefix) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7}
}

func (m *ReqGetByPrefix) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqGetByPrefix.Unmarshal(m, b)
}
func (m *ReqGetByPrefix) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqGetByPrefix.Marshal(b, m, deterministic)
}
func (m *ReqGetByPrefix) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqGetByPrefix.Merge(m, src)
}
func (m *ReqGetByPrefix) XXX_Size() int {
	return xxx_messageInfo_ReqGetByPrefix.Size(m)
}
func (m *ReqGetByPrefix) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqGetByPrefix.DiscardUnknown(m)
}

var xxx_messageInfo_ReqGetByPrefix proto.InternalMessageInfo

func (m *ReqGetByPrefix) GetBase() *ReqBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *ReqGetByPrefix) GetDbName() string {
	if m != nil {
		return m.DbName
	}
	return ""
}

func (m *ReqGetByPrefix) GetPrefix() []byte {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *ReqGetByPrefix) GetLastKey() []byte {
	if m != nil {
		return m.LastKey
	}
	return nil
}

func (m *ReqGetByPrefix) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type RespGetByPrefix struct {
	Base                 *RespBase   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	List                 []*KeyValue `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RespGetByPrefix) Reset()         { *m = RespGetByPrefix{} }
func (m *RespGetByPrefix) String() string { return proto.CompactTextString(m) }
func (*RespGetByPrefix) ProtoMessage()    {}
func (*RespGetByPrefix) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{8}
}

func (m *RespGetByPrefix) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespGetByPrefix.Unmarshal(m, b)
}
func (m *RespGetByPrefix) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespGetByPrefix.Marshal(b, m, deterministic)
}
func (m *RespGetByPrefix) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespGetByPrefix.Merge(m, src)
}
func (m *RespGetByPrefix) XXX_Size() int {
	return xxx_messageInfo_RespGetByPrefix.Size(m)
}
func (m *RespGetByPrefix) XXX_DiscardUnknown() {
	xxx_messageInfo_RespGetByPrefix.DiscardUnknown(m)
}

var xxx_messageInfo_RespGetByPrefix proto.InternalMessageInfo

func (m *RespGetByPrefix) GetBase() *RespBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *RespGetByPrefix) GetList() []*KeyValue {
	if m != nil {
		return m.List
	}
	return nil
}

type ReqBatch struct {
	Base                 *ReqBase    `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	DbName               string      `protobuf:"bytes,2,opt,name=dbName,proto3" json:"dbName,omitempty"`
	Sets                 []*KeyValue `protobuf:"bytes,3,rep,name=sets,proto3" json:"sets,omitempty"`
	Dels                 [][]byte    `protobuf:"bytes,4,rep,name=dels,proto3" json:"dels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ReqBatch) Reset()         { *m = ReqBatch{} }
func (m *ReqBatch) String() string { return proto.CompactTextString(m) }
func (*ReqBatch) ProtoMessage()    {}
func (*ReqBatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{9}
}

func (m *ReqBatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqBatch.Unmarshal(m, b)
}
func (m *ReqBatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqBatch.Marshal(b, m, deterministic)
}
func (m *ReqBatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqBatch.Merge(m, src)
}
func (m *ReqBatch) XXX_Size() int {
	return xxx_messageInfo_ReqBatch.Size(m)
}
func (m *ReqBatch) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqBatch.DiscardUnknown(m)
}

var xxx_messageInfo_ReqBatch proto.InternalMessageInfo

func (m *ReqBatch) GetBase() *ReqBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *ReqBatch) GetDbName() string {
	if m != nil {
		return m.DbName
	}
	return ""
}

func (m *ReqBatch) GetSets() []*KeyValue {
	if m != nil {
		return m.Sets
	}
	return nil
}

func (m *ReqBatch) GetDels() [][]byte {
	if m != nil {
		return m.Dels
	}
	return nil
}

type ReqIsExist struct {
	Base                 *ReqBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	DbName               string   `protobuf:"bytes,2,opt,name=dbName,proto3" json:"dbName,omitempty"`
	Key                  []byte   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqIsExist) Reset()         { *m = ReqIsExist{} }
func (m *ReqIsExist) String() string { return proto.CompactTextString(m) }
func (*ReqIsExist) ProtoMessage()    {}
func (*ReqIsExist) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{10}
}

func (m *ReqIsExist) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqIsExist.Unmarshal(m, b)
}
func (m *ReqIsExist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqIsExist.Marshal(b, m, deterministic)
}
func (m *ReqIsExist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqIsExist.Merge(m, src)
}
func (m *ReqIsExist) XXX_Size() int {
	return xxx_messageInfo_ReqIsExist.Size(m)
}
func (m *ReqIsExist) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqIsExist.DiscardUnknown(m)
}

var xxx_messageInfo_ReqIsExist proto.InternalMessageInfo

func (m *ReqIsExist) GetBase() *ReqBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *ReqIsExist) GetDbName() string {
	if m != nil {
		return m.DbName
	}
	return ""
}

func (m *ReqIsExist) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type RespIsExist struct {
	Base                 *RespBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	IsExist              bool      `protobuf:"varint,2,opt,name=isExist,proto3" json:"isExist,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RespIsExist) Reset()         { *m = RespIsExist{} }
func (m *RespIsExist) String() string { return proto.CompactTextString(m) }
func (*RespIsExist) ProtoMessage()    {}
func (*RespIsExist) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{11}
}

func (m *RespIsExist) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespIsExist.Unmarshal(m, b)
}
func (m *RespIsExist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespIsExist.Marshal(b, m, deterministic)
}
func (m *RespIsExist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespIsExist.Merge(m, src)
}
func (m *RespIsExist) XXX_Size() int {
	return xxx_messageInfo_RespIsExist.Size(m)
}
func (m *RespIsExist) XXX_DiscardUnknown() {
	xxx_messageInfo_RespIsExist.DiscardUnknown(m)
}

var xxx_messageInfo_RespIsExist proto.InternalMessageInfo

func (m *RespIsExist) GetBase() *RespBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *RespIsExist) GetIsExist() bool {
	if m != nil {
		return m.IsExist
	}
	return false
}

type ReqGetProperty struct {
	Base                 *ReqBase     `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	DbName               string       `protobuf:"bytes,2,opt,name=dbName,proto3" json:"dbName,omitempty"`
	Property             PropertyType `protobuf:"varint,3,opt,name=property,proto3,enum=proto.PropertyType" json:"property,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReqGetProperty) Reset()         { *m = ReqGetProperty{} }
func (m *ReqGetProperty) String() string { return proto.CompactTextString(m) }
func (*ReqGetProperty) ProtoMessage()    {}
func (*ReqGetProperty) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{12}
}

func (m *ReqGetProperty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqGetProperty.Unmarshal(m, b)
}
func (m *ReqGetProperty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqGetProperty.Marshal(b, m, deterministic)
}
func (m *ReqGetProperty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqGetProperty.Merge(m, src)
}
func (m *ReqGetProperty) XXX_Size() int {
	return xxx_messageInfo_ReqGetProperty.Size(m)
}
func (m *ReqGetProperty) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqGetProperty.DiscardUnknown(m)
}

var xxx_messageInfo_ReqGetProperty proto.InternalMessageInfo

func (m *ReqGetProperty) GetBase() *ReqBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *ReqGetProperty) GetDbName() string {
	if m != nil {
		return m.DbName
	}
	return ""
}

func (m *ReqGetProperty) GetProperty() PropertyType {
	if m != nil {
		return m.Property
	}
	return PropertyType_stats
}

type RespGetProperty struct {
	Base                 *RespBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Ret                  string    `protobuf:"bytes,2,opt,name=ret,proto3" json:"ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RespGetProperty) Reset()         { *m = RespGetProperty{} }
func (m *RespGetProperty) String() string { return proto.CompactTextString(m) }
func (*RespGetProperty) ProtoMessage()    {}
func (*RespGetProperty) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{13}
}

func (m *RespGetProperty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespGetProperty.Unmarshal(m, b)
}
func (m *RespGetProperty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespGetProperty.Marshal(b, m, deterministic)
}
func (m *RespGetProperty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespGetProperty.Merge(m, src)
}
func (m *RespGetProperty) XXX_Size() int {
	return xxx_messageInfo_RespGetProperty.Size(m)
}
func (m *RespGetProperty) XXX_DiscardUnknown() {
	xxx_messageInfo_RespGetProperty.DiscardUnknown(m)
}

var xxx_messageInfo_RespGetProperty proto.InternalMessageInfo

func (m *RespGetProperty) GetBase() *RespBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *RespGetProperty) GetRet() string {
	if m != nil {
		return m.Ret
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.PropertyType", PropertyType_name, PropertyType_value)
	proto.RegisterType((*ReqBase)(nil), "proto.ReqBase")
	proto.RegisterType((*RespBase)(nil), "proto.RespBase")
	proto.RegisterType((*KeyValue)(nil), "proto.KeyValue")
	proto.RegisterType((*ReqSet)(nil), "proto.ReqSet")
	proto.RegisterType((*ReqGet)(nil), "proto.ReqGet")
	proto.RegisterType((*RespGet)(nil), "proto.RespGet")
	proto.RegisterType((*ReqDelete)(nil), "proto.ReqDelete")
	proto.RegisterType((*ReqGetByPrefix)(nil), "proto.ReqGetByPrefix")
	proto.RegisterType((*RespGetByPrefix)(nil), "proto.RespGetByPrefix")
	proto.RegisterType((*ReqBatch)(nil), "proto.ReqBatch")
	proto.RegisterType((*ReqIsExist)(nil), "proto.ReqIsExist")
	proto.RegisterType((*RespIsExist)(nil), "proto.RespIsExist")
	proto.RegisterType((*ReqGetProperty)(nil), "proto.ReqGetProperty")
	proto.RegisterType((*RespGetProperty)(nil), "proto.RespGetProperty")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 488 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0x5d, 0x8b, 0xd3, 0x40,
	0x14, 0xb5, 0x49, 0xfa, 0x91, 0xdb, 0xda, 0x96, 0x51, 0x96, 0x79, 0x10, 0xb6, 0x4c, 0x5f, 0x8a,
	0x0f, 0x2b, 0x54, 0xf0, 0x07, 0x54, 0x45, 0x65, 0x45, 0x97, 0x71, 0x59, 0x50, 0x9f, 0xa6, 0xe6,
	0xba, 0x0e, 0x4d, 0x49, 0x32, 0x33, 0xd6, 0xcd, 0x83, 0xf8, 0x27, 0xfc, 0xc1, 0x32, 0x1f, 0x89,
	0x0a, 0x5b, 0x28, 0x74, 0x9f, 0x32, 0x27, 0xf7, 0xde, 0x73, 0xce, 0x3d, 0x5c, 0xb8, 0xbf, 0x45,
	0xad, 0xc5, 0x35, 0x9e, 0x95, 0xaa, 0x30, 0x05, 0xe9, 0xba, 0x0f, 0x3b, 0x85, 0x3e, 0xc7, 0x6a,
	0x25, 0x34, 0x92, 0x87, 0xd0, 0xdd, 0xea, 0x6b, 0x99, 0xd1, 0xce, 0xac, 0xb3, 0x48, 0xb9, 0x07,
	0xec, 0x12, 0x06, 0x1c, 0x75, 0xb9, 0xbf, 0x83, 0x3c, 0x82, 0x14, 0x95, 0x2a, 0xd4, 0xf3, 0x22,
	0x43, 0x1a, 0xcf, 0x3a, 0x8b, 0x98, 0xff, 0xfd, 0x61, 0x67, 0x1c, 0xa0, 0x89, 0x9f, 0x71, 0x80,
	0x2d, 0x61, 0x70, 0x8e, 0xf5, 0x95, 0xc8, 0xbf, 0x23, 0x99, 0x42, 0xbc, 0xc1, 0xda, 0x71, 0x8e,
	0xb8, 0x7d, 0xda, 0x99, 0x9d, 0x2d, 0xd1, 0xc8, 0xfd, 0xf3, 0x80, 0x21, 0xf4, 0x38, 0x56, 0x1f,
	0xd0, 0x10, 0x06, 0xc9, 0x5a, 0x68, 0x74, 0x23, 0xc3, 0xe5, 0xd8, 0x6f, 0x74, 0x16, 0xf6, 0xe0,
	0xae, 0x46, 0x4e, 0xa0, 0x97, 0xad, 0xdf, 0x89, 0xad, 0x27, 0x49, 0x79, 0x40, 0xe4, 0x14, 0xa2,
	0xcd, 0xce, 0xd9, 0x1c, 0x2e, 0x27, 0x61, 0xb2, 0xb1, 0xc2, 0xa3, 0xcd, 0x8e, 0x5d, 0x39, 0x99,
	0x57, 0x47, 0xca, 0x84, 0xa5, 0xe2, 0x76, 0x29, 0xf6, 0xde, 0x26, 0xad, 0x4b, 0x4b, 0x3c, 0xff,
	0x8f, 0x78, 0xd2, 0x12, 0xfb, 0x98, 0x03, 0xb3, 0x37, 0x1a, 0xed, 0x37, 0xfa, 0x11, 0x52, 0x8e,
	0xd5, 0x0b, 0xcc, 0xd1, 0xe0, 0x1d, 0x7b, 0xfd, 0xdd, 0x81, 0xb1, 0x0f, 0x61, 0x55, 0x5f, 0x28,
	0xfc, 0x2a, 0x6f, 0x8e, 0x12, 0x38, 0x81, 0x5e, 0xe9, 0x58, 0x82, 0x46, 0x40, 0x84, 0x42, 0x3f,
	0x17, 0xda, 0x9c, 0x63, 0xed, 0xae, 0x63, 0xc4, 0x1b, 0x68, 0x2f, 0x20, 0x97, 0x5b, 0x69, 0x68,
	0xd7, 0xdd, 0x93, 0x07, 0xec, 0x33, 0x4c, 0x42, 0x84, 0xad, 0xad, 0x83, 0xa2, 0x9c, 0x43, 0x92,
	0x4b, 0x6d, 0x68, 0x34, 0x8b, 0x6f, 0x0b, 0xd3, 0x15, 0xd9, 0x2f, 0x7b, 0xe8, 0xd5, 0x4a, 0x98,
	0x2f, 0xdf, 0x8e, 0x5a, 0x76, 0x0e, 0x89, 0x46, 0xa3, 0x69, 0xbc, 0x47, 0xcc, 0x16, 0x09, 0x81,
	0x24, 0xc3, 0x5c, 0xd3, 0x64, 0x16, 0x2f, 0x46, 0xdc, 0xbd, 0xd9, 0x27, 0x00, 0x8e, 0xd5, 0x1b,
	0xfd, 0xf2, 0x46, 0xea, 0xbb, 0x3e, 0xbe, 0xb7, 0x30, 0xb4, 0x99, 0x34, 0xe4, 0x07, 0xa5, 0x46,
	0xa1, 0x2f, 0x7d, 0xbf, 0xa3, 0x1f, 0xf0, 0x06, 0xb2, 0x9f, 0xcd, 0x75, 0x5c, 0xa8, 0xa2, 0x44,
	0x65, 0xea, 0xa3, 0xdc, 0x3e, 0x81, 0x41, 0x19, 0x78, 0x9c, 0xe5, 0xf1, 0xf2, 0x41, 0x98, 0x6f,
	0xe8, 0x2f, 0xeb, 0x12, 0x79, 0xdb, 0xc4, 0x5e, 0xb7, 0x67, 0xd0, 0xea, 0x1f, 0xb4, 0xd0, 0x14,
	0x62, 0x85, 0x26, 0xa8, 0xdb, 0xe7, 0xe3, 0x67, 0x30, 0xfa, 0x57, 0x83, 0xa4, 0xd0, 0xd5, 0x46,
	0x18, 0x3d, 0xbd, 0x47, 0xc6, 0x00, 0x3f, 0x94, 0x34, 0x98, 0x61, 0x2e, 0xea, 0x69, 0x87, 0x0c,
	0xa1, 0x2f, 0x0b, 0x5f, 0x8c, 0xd6, 0x3d, 0xc7, 0xff, 0xf4, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xc8, 0xda, 0x37, 0x34, 0x54, 0x05, 0x00, 0x00,
}
